//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localtunnel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localtunnel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows untrusted certificate (use only for development/testing purposes).
        /// </summary>
        internal static string AllowUntrustedCertificatesDescription {
            get {
                return ResourceManager.GetString("AllowUntrustedCertificatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, opens the webpage in the browser..
        /// </summary>
        internal static string BrowserDescription {
            get {
                return ResourceManager.GetString("BrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{Label}] Connection closed..
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{Label}] Connection error: {Error}, operation: {Operation}..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating tunnel....
        /// </summary>
        internal static string CreatingTunnel {
            get {
                return ResourceManager.GetString("CreatingTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve DNS address for &apos;{0}&apos;!.
        /// </summary>
        internal static string DnsResolutionFailed {
            get {
                return ResourceManager.GetString("DnsResolutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host to proxy requests to..
        /// </summary>
        internal static string HostDescription {
            get {
                return ResourceManager.GetString("HostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a tunnel that exposes a HTTP server..
        /// </summary>
        internal static string HttpProxy {
            get {
                return ResourceManager.GetString("HttpProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a tunnel that exposes a HTTPS server..
        /// </summary>
        internal static string HttpsProxy {
            get {
                return ResourceManager.GetString("HttpsProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of maximum allowed connections..
        /// </summary>
        internal static string MaximumConnectionsDescription {
            get {
                return ResourceManager.GetString("MaximumConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the request is proxied as received and no HTTP headers are reinterpreted..
        /// </summary>
        internal static string PassthroughDescription {
            get {
                return ResourceManager.GetString("PassthroughDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port to proxy requests to..
        /// </summary>
        internal static string PortDescription {
            get {
                return ResourceManager.GetString("PortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of bytes to use for the receive buffer..
        /// </summary>
        internal static string ReceiveBufferSizeDescription {
            get {
                return ResourceManager.GetString("ReceiveBufferSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending HTTP GET request ({URI})....
        /// </summary>
        internal static string SendingHttpGet {
            get {
                return ResourceManager.GetString("SendingHttpGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname of the server to use..
        /// </summary>
        internal static string ServerDescription {
            get {
                return ResourceManager.GetString("ServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the subdomain to use, if not specified a random subdomain name is used..
        /// </summary>
        internal static string SubdomainDescription {
            get {
                return ResourceManager.GetString("SubdomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel {Id} created (max connections: {MaxConnections}, Port: {Port}, URI: {URI}).
        /// </summary>
        internal static string TunnelCreated {
            get {
                return ResourceManager.GetString("TunnelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables detailed verbose output..
        /// </summary>
        internal static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
    }
}
