//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localtunnel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localtunnel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether untrusted certificates are allowed (use only for development/testing purposes)..
        /// </summary>
        internal static string AllowUntrustedCertificatesDescription {
            get {
                return ResourceManager.GetString("AllowUntrustedCertificatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, opens the webpage in the browser..
        /// </summary>
        internal static string BrowserDescription {
            get {
                return ResourceManager.GetString("BrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{Label}] Connection closed..
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{Label}] Connection error: {Error}, operation: {Operation}..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating tunnel....
        /// </summary>
        internal static string CreatingTunnel {
            get {
                return ResourceManager.GetString("CreatingTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating tunnel with {Connections} concurrent connection(s)..
        /// </summary>
        internal static string CreatingTunnelWithNConnections {
            get {
                return ResourceManager.GetString("CreatingTunnelWithNConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current active connections.
        /// </summary>
        internal static string CurrentActiveConnections {
            get {
                return ResourceManager.GetString("CurrentActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve DNS address for &apos;{0}&apos;..
        /// </summary>
        internal static string DnsResolutionFailed {
            get {
                return ResourceManager.GetString("DnsResolutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host to proxy requests to..
        /// </summary>
        internal static string HostDescription {
            get {
                return ResourceManager.GetString("HostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a tunnel that exposes a HTTP server..
        /// </summary>
        internal static string HttpProxy {
            get {
                return ResourceManager.GetString("HttpProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a tunnel that exposes a HTTPS server..
        /// </summary>
        internal static string HttpsProxy {
            get {
                return ResourceManager.GetString("HttpsProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max concurrent connections.
        /// </summary>
        internal static string MaxConcurrentConnections {
            get {
                return ResourceManager.GetString("MaxConcurrentConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of maximum allowed connections..
        /// </summary>
        internal static string MaximumConnectionsDescription {
            get {
                return ResourceManager.GetString("MaximumConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onlice since.
        /// </summary>
        internal static string OnlineSince {
            get {
                return ResourceManager.GetString("OnlineSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the request is proxied as received and no HTTP headers are reinterpreted..
        /// </summary>
        internal static string PassthroughDescription {
            get {
                return ResourceManager.GetString("PassthroughDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port to proxy requests to..
        /// </summary>
        internal static string PortDescription {
            get {
                return ResourceManager.GetString("PortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Ctrl] + [C] to exit..
        /// </summary>
        internal static string PressToExit {
            get {
                return ResourceManager.GetString("PressToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of bytes to use for the receive buffer..
        /// </summary>
        internal static string ReceiveBufferSizeDescription {
            get {
                return ResourceManager.GetString("ReceiveBufferSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string SchemeHttp {
            get {
                return ResourceManager.GetString("SchemeHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS.
        /// </summary>
        internal static string SchemeHttps {
            get {
                return ResourceManager.GetString("SchemeHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending HTTP GET request ({URI})....
        /// </summary>
        internal static string SendingHttpGet {
            get {
                return ResourceManager.GetString("SendingHttpGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname of the server to use..
        /// </summary>
        internal static string ServerDescription {
            get {
                return ResourceManager.GetString("ServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting browser at {Url}....
        /// </summary>
        internal static string StartingBrowser {
            get {
                return ResourceManager.GetString("StartingBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the subdomain to use, if not specified a random subdomain name is used..
        /// </summary>
        internal static string SubdomainDescription {
            get {
                return ResourceManager.GetString("SubdomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel {Id} created (max connections: {MaxConnections}, Port: {Port}, URI: {URI}).
        /// </summary>
        internal static string TunnelCreated {
            get {
                return ResourceManager.GetString("TunnelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Id.
        /// </summary>
        internal static string TunnelId {
            get {
                return ResourceManager.GetString("TunnelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (tunnel offline).
        /// </summary>
        internal static string TunnelOffline {
            get {
                return ResourceManager.GetString("TunnelOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tunnel online @ tunnelclient.
        /// </summary>
        internal static string TunnelOnline {
            get {
                return ResourceManager.GetString("TunnelOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string TunnelURI {
            get {
                return ResourceManager.GetString("TunnelURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables detailed verbose output..
        /// </summary>
        internal static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
    }
}
